[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
nft_staking = "4cDnjHit334grU5ias9yAyNhhVwGtwbk4ph9EvjWK1UE"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
